"""initial

Revision ID: 48c330bee89d
Revises: 
Create Date: 2018-10-23 14:28:18.869787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c330bee89d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniq', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('access', sa.String(length=200), nullable=False),
    sa.Column('refresh', sa.String(length=200), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uniq', 'users', ['uniq', 'provider'], unique=True)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniq', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uniq')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    op.drop_index('uniq', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
